general {
    lock_cmd = /home/miles/.local/bin/qs-lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dpms on
    ignore_dbus_inhibit = false
}

# 15 min: lock screen
listener {
    timeout = 900
    on-timeout = /home/miles/.local/bin/qs-lock
}

# 20 min: turn off display
listener {
    timeout = 1200
    on-timeout = hyprctl dpms off
    on-resume = hyprctl dpms on
}

# 60 min: suspend
listener {
    timeout = 3600
    on-timeout = systemctl suspend
}
