general {
    lock_cmd = pidof swaylock || swaylock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}
    #before_sleep_cmd = pidof swaylock || swaylock

# 15 min: lock screen
listener {
    timeout = 900
    on-timeout = pidof swaylock || swaylock
}
    #on-resume = hyprctl dispatch dpms on

# 16 min: turn off display
listener {
    timeout = 960
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
