return {
    gaps_in = 5,
    gaps_out = 10,
    border_size = 1,
    active_border = { colors = { "rgba(334155ee)","rgba(0f172aee)" }, angle = 45 },
    inactive_border = "rgba(1e293baa)",
    rounding = 12,
    rounding_power = 3.0,
    active_opacity = 1,
    inactive_opacity = 1,
    shadow_enabled = false,
    shadow_range = 20,
    shadow_render_power = 4,
    shadow_color = "rgba(00000099)",
    blur_enabled = true,
    blur_size = 5,
    blur_passes = 2,
    blur_vibrancy = 1696,
}
