#################
### AUTOSTART ###
#################
exec-once = uwsm finalize QT_QPA_PLATFORMTHEME && systemctl --user start xdg-desktop-portal-hyprland.service xdg-desktop-portal.service
exec-once = foot --server
exec-once = ~/.config/hypr/scripts/start_zen_bg.sh
exec-once = hyprpaper
exec-once = quickshell --path ~/.config/quickshell/shell.qml & $rog
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = nm-applet --indicator
exec-once = /usr/libexec/kf6/polkit-kde-authentication-agent-1
exec-once = hyprsunset -t 5000
exec-once = ~/.config/hypr/scripts/switch_theme.sh nero

exec-once = cliphist list | tail -n +501 | cliphist delete

exec-once = xwaylandvideobridge
exec-once = systemctl --user start hide-xwlvb.service
